services:
  python-app:
    build: .
    container_name: python-app
    restart: always
    depends_on:
      - mariadb
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: mydb
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    network_mode: "host"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    network_mode: "host"

volumes:
  mariadb_data:
