# Generated by Django 5.1rc1 on 2024-10-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_code', models.CharField(max_length=100)),
                ('option_description', models.CharField(max_length=100)),
                ('option_text', models.CharField(max_length=2000)),
            ],
        ),
    ]
