# Generated by Django 5.1rc1 on 2024-11-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    def populate_db(apps, schema_editor):
        SecurityOptions = apps.get_model("web_server", "SecurityOptions")
        option1 = SecurityOptions(option_code="TLS_AES_256_GCM_SHA384", option_description="TLS 1.3 - Best for Security", option_text="This is an option used for blah blah\nAlso blah blah", is_selected=True)
        option1.save()
        option2 = SecurityOptions(option_code="TLS_AES_128_GCM_SHA256", option_description="TLS 1.3 - Best for Performance", option_text="This is an option used for blah blah<br><br>Also blah blah", is_selected=False)
        option2.save()
        option3 = SecurityOptions(option_code="TLS_CHACHA20_POLY1305_SHA256", option_description="TLS 1.3  - Best for Mobile Devices", option_text="This is an option used for blah blah<br><br>Also blah blah", is_selected=False)
        option3.save()
        option4 = SecurityOptions(option_code="ECDHE-ECDSA-AES256-GCM-SHA384", option_description="TLS 1.2 - Best for Security", option_text="This is an option used for blah blah\nAlso blah blah", is_selected=False)
        option4.save()
        option5 = SecurityOptions(option_code="ECDHE-ECDSA-AES128-GCM-SHA256", option_description="TLS 1.2 - Best for Performance", option_text="This is an option used for blah blah<br><br>Also blah blah", is_selected=False)
        option5.save()
        option6 = SecurityOptions(option_code="ECDHE-ECDSA-CHACHA20-POLY1305", option_description="TLS 1.2 - Best for Mobile Devices", option_text="This is an option used for blah blah<br><br>Also blah blah", is_selected=False)
        option6.save()

    dependencies = [
        ('web_server', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
