# Generated by Django 5.1rc1 on 2024-10-31 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_server', '0002_securityoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedOption',
            fields=[
                ('option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web_server.securityoptions')),
            ],
        ),
    ]
