# Generated by Django 5.1rc1 on 2024-10-31 15:24

from django.db import migrations

def populate_db(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SecurityOptions = apps.get_model("web_server", "SecurityOptions")
    option1 = SecurityOptions(option_code="ECDHE-ECDSA-AES256-GCM-SHA384", option_description="Best for Security", option_text="This is an option used for blah blah<br><br>Also blah blah")
    option1.save()
    option2 = SecurityOptions(option_code="ECDHE-ECDSA-AES128-GCM-SHA256", option_description="Best for Performance", option_text="This is an option used for blah blah<br><br>Also blah blah")
    option2.save()
    option3 = SecurityOptions(option_code="ECDHE-ECDSA-CHACHA20-POLY1305", option_description="Best for Mobile Devices", option_text="This is an option used for blah blah<br><br>Also blah blah")
    option3.save()
    SelectedOption = app.get_model("web_server", "SelectedOption")
    first_option = SecurityOptions.objects.first()
    SelectedOption.objects.create(option=first_option)
    

class Migration(migrations.Migration):

    dependencies = [
        ('web_server', '0003_selectedoption'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]

